import { StyleSheet } from 'react-native';

const colors = {
  primary: '#4287f5',
  secondary: '#55c6f2',
  accent: '#cff7b2',
  danger: '#ffd7d4',
  background: '#f5fcff',
  textPrimary: '#333',
  textSecondary: '#888',
  lightGray: '#ebf4ff',
};

const typography = {
title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 10,
    textAlign: 'center',
},
  buttonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    textTransform: 'uppercase',
  },
  inputText: {
    fontSize: 18,
    color: colors.textPrimary,
  },
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: colors.background,
  },
  title: typography.title,
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  textInput: {
    flex: 1,
    fontSize: typography.inputText.fontSize,
    padding: 7,
    paddingHorizontal: 15,
    borderColor: colors.lightGray,
    borderWidth: 1,
    borderRadius: 10,
  },
  button: {
    // padding: 10,
    // borderRadius: 5,
    // alignItems: 'center',
    // justifyContent: 'center',
    // backgroundColor: colors.primary,
    // marginVertical: 10,
    // width: '100%',
    padding: 10,
    borderRadius: 5,
    margin: 10,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#55c6f2',
  },
  buttonText: typography.buttonText,
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  listItem: {
    flex: 1,
    backgroundColor: colors.lightGray,
    padding: 10,
    borderRadius: 10,
    marginRight: 5,
  },
  deleteButton: {
    backgroundColor: colors.danger,
    padding: 10,
    borderRadius: 10,
  },
  submitButton: {
    width: 45,
    height: 45,
    backgroundColor: colors.accent,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  startWorkoutButton: {
    padding: 15,
    borderRadius: 5,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  flatList: {
    flexGrow: 1,
    marginVertical: 10,
  },

  // Journal Screen
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#f0f0f0',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  section: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: '#ffffff',
    borderRadius: 8,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  info: {
    fontSize: 18,
    marginBottom: 5,
  },
  breakdownContainer: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: '#ccc',
  },
  breakdownTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  breakdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
  },
  breakdownText: {
    fontSize: 16,
  },

  // Current Workout Screen
  exercisesContainer: {
    flex: 1,
    padding: 5,
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  flatListStyle: {
    height: 150,
  },
  setText: {
    padding: 0,
    margin: 0,
    alignItems: 'center',
    fontSize: 17,
  },
  newSetStyle: {
    backgroundColor: '#55c6f2',
    color: 'white',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    padding: 10,
    paddingVertical: 7,
    fontSize: 15,
  },
  prevNextButtons: {
    backgroundColor: '#55c6f2',
    color: 'white',
    borderRadius: 15,
    fontSize: 25,
    paddingVertical: 6,
    paddingHorizontal: 12,
    margin: 2,
    width: 40,
    bottom: 20,
  },
  prevNextButtonsEdge: {
    backgroundColor: '#a5ddf2',
    color: 'white',
    borderRadius: 15,
    fontSize: 25,
    paddingVertical: 6,
    paddingHorizontal: 12,
    margin: 2,
    width: 40,
    bottom: 20,
  },
  horizontalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    // margin: 5,
    padding: 0,
  },
  horizontalRowWrapper: {
    marginBottom: 7,
    padding: 0,
  },
  currentExercise: {
    padding: 0,
    width: '55%',
    textAlign: 'center',
    fontSize: 30,
    // backgroundColor: '#e6fcec',
    height: 90,
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    
  },
  timerText: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
    // fontSize: 300,
  },
  timerWrapper: {
    margin: 30,
  },
  numInput: {
    height: 40,
    marginVertical: 0,
    marginHorizontal: 5,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 0,
    fontSize: 17,
    borderRadius: 7,
  },
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#F5FCFF',
  },
  title: {
    marginBottom: 10,
    fontSize: 24,
    fontWeight: 'bold',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 10,
  },
  textBoxes: {
    flex: 1,
    fontSize: 18,
    padding: 7,
    paddingHorizontal: 15,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 10,
  },
  item: {
    backgroundColor: '#ebf4ff',
    borderRadius: 15,
    fontSize: 17,
    paddingVertical: 6,
    paddingHorizontal: 12,
    margin: 2,
  },
  itemX: {
    backgroundColor: '#ffd7d4',
    borderRadius: 15,
    fontSize: 17,
    paddingVertical: 6,
    paddingHorizontal: 12,
    margin: 2,
  },
  flatListStyle: {
    flexGrow: 1,
    margin: 5,
    marginBottom: 10,
  },
  buttons: {
    padding: 10,
    borderRadius: 5,
    margin: 10,
    backgroundColor: '#4287f5',
    width: '80%',
    alignSelf: 'center',
  },
  buttonText: {
    color: 'white',
    textTransform: 'uppercase',
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'center',
  },
  submit: {
    backgroundColor: '#cff7b2',
    color: 'white',
    width: 45,
    height: 45,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  submitText: {
    fontSize: 24,
    color: 'black',
  },
  listRow: {
    flexDirection: 'row',
  },
  startWorkout: {
    padding: 10,
    borderRadius: 5,
    margin: 10,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#55c6f2',
  },
});

export { styles, colors, typography };